import prisma from "../../prisma/prismaClient.js";
import auditLogger from "../../utils/auditLogger.js";
import { hashPassword } from "../../utils/hashPassword.js";

/**
 * Fetch all users within the admin's college.
 * Excludes super-admins to prevent horizontal privilege escalation or viewing.
 */
export const fetchUsers = async (collegeId, requestingUserRole) => {
    const where = { collegeId };
    if (requestingUserRole !== 'SUPER_ADMIN') {
        where.role = { name: { not: 'SUPER_ADMIN' } };
    }
    return await prisma.user.findMany({
        where,
        select: {
            id: true,
            email: true,
            name: true,
            isLocked: true,
            failedLoginAttempts: true,
            lastLogin: true,
            createdAt: true,
            role: {
                select: { name: true }
            }
        },
        orderBy: { createdAt: 'desc' }
    });
};

/**
 * Provision a new user.
 * Attack Model Mitigation:
 * - Admin cannot provision SUPER_ADMIN.
 * - Password is automatically hashed before DB storage.
 */
export const provisionUser = async (data, adminUser) => {
    const { email, name, password, roleName } = data;

    // Fetch the role ID
    const role = await prisma.role.findUnique({ where: { name: roleName } });
    if (!role) throw new Error("Invalid role specified");

    // Prevent privilege escalation
    if (roleName === "SUPER_ADMIN" && adminUser.role !== "SUPER_ADMIN") {
        throw new Error("Unauthorized to provision SUPER_ADMIN accounts");
    }

    const existingUser = await prisma.user.findUnique({ where: { email } });
    if (existingUser) throw new Error("Email already registered");

    const hashedPassword = await hashPassword(password);

    const newUser = await prisma.user.create({
        data: {
            email,
            name,
            passwordHash: hashedPassword,
            roleId: role.id,
            collegeId: adminUser.collegeId // Strict scoping to admin's college
        },
        select: {
            id: true,
            email: true,
            name: true,
            role: { select: { name: true } }
        }
    });

    await auditLogger({
        userId: adminUser.id,
        action: "USER_PROVISIONED",
        resourceType: "AUTH",
        resourceId: newUser.id,
        severity: "WARNING", // Provisioning is a sensitive action
        details: { provisionedRole: roleName }
    });

    return newUser;
};

/**
 * Lock or Unlock a user account.
 * Mitigates insider threat by logging exact action.
 */
export const changeUserLockStatus = async (targetUserId, isLocked, adminUser) => {
    const targetUser = await prisma.user.findUnique({
        where: { id: targetUserId },
        include: { role: true }
    });

    if (!targetUser) throw new Error("User not found");
    // collegeId comes from JWT payload directly
    if (targetUser.collegeId !== adminUser.collegeId) throw new Error("Unauthorized");

    // Prevent locking yourself or superior admins
    if (targetUser.id === adminUser.id) throw new Error("Cannot modify your own lock status");
    if (targetUser.role.name === "SUPER_ADMIN") throw new Error("Cannot lock a SUPER_ADMIN");

    const updatedUser = await prisma.user.update({
        where: { id: targetUserId },
        data: { 
            isLocked,
            failedLoginAttempts: isLocked ? targetUser.failedLoginAttempts : 0 // Reset on unlock
        },
        select: { id: true, email: true, isLocked: true }
    });

    // If locked by admin, revoke all sessions immediately to kick them out
    if (isLocked) {
        await prisma.session.updateMany({
            where: { userId: targetUserId, isRevoked: false },
            data: { isRevoked: true }
        });
    }

    await auditLogger({
        userId: adminUser.id,
        action: isLocked ? "USER_LOCKED_BY_ADMIN" : "USER_UNLOCKED_BY_ADMIN",
        resourceType: "AUTH",
        resourceId: targetUserId,
        severity: "CRITICAL"
    });

    return updatedUser;
};

/**
 * Fetch Audit Logs for the SOC Dashboard.
 * Strict college-level scoping.
 */
export const fetchAuditLogs = async (collegeId, limit = 50) => {
    // We get audit logs generated by users within this college
    return await prisma.auditLog.findMany({
        where: {
            user: {
                collegeId: collegeId
            }
        },
        include: {
            user: {
                select: { email: true, name: true, role: { select: { name: true } } }
            }
        },
        orderBy: { timestamp: 'desc' },
        take: limit
    });
};

/**
 * Fetch System Anomalies (Threat detection).
 * Used for SIEM monitoring by admins.
 */
export const fetchAnomalies = async (collegeId, limit = 20) => {
    return await prisma.abuseAnomaly.findMany({
        where: {
            form: { collegeId: collegeId }
        },
        include: {
            form: { select: { title: true } }
        },
        orderBy: { createdAt: 'desc' },
        take: limit
    });
};

/**
 * Fetch real-time security intelligence metrics for the SOC Dashboard.
 */
export const fetchSecurityMetrics = async (collegeId) => {
    const twentyFourHoursAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);

    const baseWhere = {
        user: { collegeId }
    };

    const [
        failedLogins,
        lockedAccounts,
        totalEvents,
        criticalEvents,
        highEvents,
        recentThreats
    ] = await Promise.all([
        prisma.auditLog.count({
            where: { ...baseWhere, action: 'LOGIN_FAILED', timestamp: { gte: twentyFourHoursAgo } }
        }),
        prisma.user.count({
            where: { collegeId, isLocked: true }
        }),
        prisma.auditLog.count({
            where: { ...baseWhere, timestamp: { gte: twentyFourHoursAgo } }
        }),
        prisma.auditLog.count({
            where: { ...baseWhere, severity: 'CRITICAL', timestamp: { gte: twentyFourHoursAgo } }
        }),
        prisma.auditLog.count({
            where: { ...baseWhere, severity: 'WARNING', timestamp: { gte: twentyFourHoursAgo } }
        }),
        prisma.auditLog.findMany({
            where: { ...baseWhere, severity: { in: ['CRITICAL', 'WARNING'] }, timestamp: { gte: twentyFourHoursAgo } },
            orderBy: { timestamp: 'desc' },
            take: 5,
            include: { user: { select: { email: true } } }
        })
    ]);

    // Calculate a basic risk score out of 100
    // Higher means more risk
    let riskScore = 0;
    riskScore += criticalEvents * 10;
    riskScore += highEvents * 5;
    riskScore += failedLogins * 2;
    riskScore += lockedAccounts * 15;
    
    // Cap at 100
    riskScore = Math.min(riskScore, 100);

    return {
        failedLogins,
        lockedAccounts,
        totalEvents,
        criticalEvents,
        highEvents,
        riskScore,
        recentThreats
    };
};
